### ISSUE TITLE
Question :  where do you test if a value is a right value 

### ISSUE THREAD

**Issue by RoelofWobben** [k0001/safe-money#31]
Hello, 

For inspiration for my own project im looking at yours. 
but I wonder. Do you test if a value is a valid currency so 1.234 is invalid. 

And if so, where do you test this ? 

Regards, 

Roelof

**Comment by k0001** [comment]
Hey @RoelofWobben, thanks for reaching out.

Unfortunately, I don't exactly understand the question you are asking. Could you give concrete examples of the currency you have in mind (e.g., USD, EUR, etc.), and the amount you think would be invalid for it (e.g., 1.234 USD is not an amount that can be represented physically with bills and coins).

I suspect your question has to do with the difference between `Dense` and `Discrete`. In the example I gave above, 1.234 USD could only be represented as a `Dense "USD"` in `safe-money`, whereas something like 5.67 could be represented as a `Discrete "USD" "cent"` as well.

**Comment by RoelofWobben** [comment]
I just wonder where and how you test that for example `Eur 1.234 ` is invalid but `Eur 1.23` is valid

**Comment by k0001** [comment]
Ah, I see. There is no “testing” necessary since all of this information is kept at the type level. As far as `safe-money` is concerned, both EUR 1.234 and EUR 1.23 are acceptable values. However, while EUR 1.234 is only representable as a `Dense "EUR"`, EUR 1.23 is representable as both `Dense "EUR"` and `Discrete "EUR" "cent"`. The closest thing to “testing” this input is the implementation of the `discreteFromDense` function.

In this article I explain in detail how all of these things work https://ren.zone/articles/safe-money :)

**Comment by RoelofWobben** [comment]
Thanks, for me it's another case.  ` Eur 1.234` is not acceptable because in my oponion is not valid. You cannot have 1/10 of a cent.

**Comment by k0001** [comment]
@RoelofWobben EUR 1.234 is certainly not an amount that you can't represent in a number of bills and coins, which is why the type system prevents it from being representable as a `Discrete "EUR" "cent"`. I agree with you there. But you still can use 1/10 of a cent, as you say, for intermediate calculations. That is what `Dense "EUR"` is for. Otherwise, calculations become lossy.

In your case, `Discrete "EUR" "cent"` is what you are looking for. As long as you can construct a value of that type, you can be sure that it will be representable as a phyisical amount of bills and coins :)

**Comment by k0001** [comment]
@RoelofWobben by the way, how are getting your input? Do you have a string like "1.23" or what? If that's the case, then simply calling [`discreteFromDecimal`](https://hackage.haskell.org/package/safe-money-0.7/docs/Money.html#v:discreteFromDecimal) with an expected return type of `Maybe (Discrete "EUR" "cent")` will do the trick. Unrepresentable amounts (such as `1.234`) will return `Nothing`.

**Comment by RoelofWobben** [comment]
Yep, I get the input from a `getline` so it's a string. 
Can you give me a example how to use the `discreteFromDecimal`  function

**Comment by k0001** [comment]
Sure. Here is an example that succeeds with `1.23`, but fails with `1.234`:


```
> discreteFromDecimal Nothing '.' 1 "1.23" :: Maybe (Discrete "EUR" "cent")
Just (Discrete "EUR" 100%1 123)

> discreteFromDecimal Nothing '.' 1 "1.234" :: Maybe (Discrete "EUR" "cent")
Nothing
```
