### ISSUE TITLE
Fix docs in discreteToDecimal

### ISSUE THREAD

**Issue by k0001** [k0001/safe-money#45]

**Comment by nlander** [comment]
I am not sure if this is a bug or an issue with the documentation, but `discreteToDecimal` does not work as I would expect when dealing with smaller units of the currency, such as cents of USD.
For example:
```
> let twoCentsDense = dense' (2%100)
> denseToDecimal defaultDecimalConf Round (twoCentsDense :: Dense "USD")
"0.20"
```
I would expect `denseToDecimal` to display `"0.02"` here, because `(2%100)` is 2 cents not 20 cents.

**Comment by k0001** [comment]
Thanks for the report. Yes, this seems to be an issue with the rendering of
small amounts. I'll fix it as soon as possible.

**Comment by k0001** [comment]
@nlander this issue has been fixed and relevant tests added. I pushed `safe-money-0.8.1` up to Hackage.
