### ISSUE TITLE
Fix naming of KPW `chon`

### ISSUE THREAD

**Issue by QuietJoon** [k0001/safe-money#7]
I have no Idea about the public statements of the romanization of Noth Korea Won and how could I get the information.
However, `KPW chon` and and `KRW jeon` are written in the same character `전` and spoken in same pronunciation.

I do not know where you can reference **responsible** romanization source about the name of KPW `전`, but this may need to be revised.

South Korea has a responsible resource: [Bank of Korea](http://www.bok.or.kr/broadcast.action?menuNaviId=1950), 
but I'm not sure North Korea also has a responsible source about their currency unit's romanization name.

**Comment by k0001** [comment]
@QuietJoon thanks for the report.

Is it worth changing this? We'll end up with similar situations for different currencies, since usually the only official name is the one in the official language of the region, like 전 in this case, but then romanizations fail in one or other way (most commonly for languages not using the latin script).

We can easily add `Scale` instances for all of the different variants, but then maybe that becomes noisy. And/or we could add `Scale` instances with the official name in the official script, but I think that would probably just add noise since usually people don't like using non-ASCII characters in source code files.

Do you have some more thoughts about this?

**Comment by k0001** [comment]
@QuietJoon I searched online, and most of the references I could find say "chon". Frankly, I don't think it matters that much, one can easily have both "chon" and "jeon" and it will work just fine. That is, you don't need to pick just one. For example, today, `Scale "ETH" "kwei" ~ Scale "ETH" "babbage"`. If you feel strongly about this, let me know and I'll add "jeon" as well.

**Comment by k0001** [comment]
I'll close this for the time being.
